version: '3.8'
services:
  chatbot:
    build: .
    ports:
      - "10000:10000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=10000
    command: flask run --host=0.0.0.0 --port=10000
